### ISSUE TITLE
Avconv missing metadata

### ISSUE THREAD

**Issue by attenzione** [ruby-av/av#3]
Avconv video

```
Av.cli.identify('video.mov')
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["avconv", "ffmpeg"], using: Avconv
[AV] Running command: avconv -i "video.mov" 2>&1
=> {:size=>"1920x1080", :aspect=>1.7777777777777777}
```

FFmpeg video

```
Av.cli.identify('video.mov')
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: ffmpeg -i "video.mov" 2>&1
=> {:length=>"0:00:26.73", :fps=>60, :size=>"1920x1080", :aspect=>1.7777777777777777}
```

Avconv audio

```
Av.cli.identify('audio.mp3')
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["avconv", "ffmpeg"], using: Avconv
[AV] Running command: avconv -i "audio.mp3" 2>&1
=> {:audio_encode=>"mp3", :audio_bitrate=>"44100 Hz", :audio_channels=>"1 channels"}
```

FFmpeg audio

```
Av.cli.identify('audio.mp3')
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Found ["ffmpeg"], using: Ffmpeg
[AV] Running command: ffmpeg -i "audio.mp3" 2>&1
=> {:length=>"0:00:02.66", :audio_encode=>"mp3", :audio_bitrate=>"44100 Hz", :audio_channels=>"mono"}
```

Avconv version

```
avconv version 11.2, Copyright (c) 2000-2014 the Libav developers
  built on Jan 26 2015 11:47:25 with Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Hyper fast Audio and Video encoder
```

**Comment by owahab** [comment]
I think that was fixed in #5, no?

**Comment by attenzione** [comment]
no, it's not fixed, i just added some more information to meta. 
problem still exists in identify method https://github.com/ruby-av/av/blob/master/lib/av/commands/base.rb#L94 
it can't find resolution in command result

**Comment by attenzione** [comment]
Just updated `libav` to version `11.3`, problem disappeared. 
Not gem issue, so some description about version requirements could be added.

**Comment by owahab** [comment]
Can you confirm the issue on 11.x < 11.3?

**Comment by attenzione** [comment]
With avconv 11.2 gem identify function returns almost nothing about video.
However, avconv command line execution  returns it.
